### ISSUE TITLE
1.21 Update

### ISSUE THREAD

**Issue by Kaytra** [Stoupy51/RandomMobSizes#1]
With the release of 1.21, the datapack stopped working. I have not tested the mod version to see if it is having the same issue.

The datapack no longer working in 1.21 is due to Minecraft no longer looking for the 'functions' folder to run functions, and instead looking for the 'function' folder. It should be a simple 15-20 minute fix, if you plan on updating the pack.
If not, I hope that this explanation helps someone wondering why it doesn't work.

**Comment by Stoupy51** [comment]
Yes, the version was for 1.20.5 to 1.20.6.
I just updated it for 1.21
